apiVersion: samplecontroller.evan.com/v1alpha1
kind: Evan
metadata:
  name: example-evan
  namespace: default
spec:
  deploymentConfig:
    name:
    replicas: 2
    image: evanraisul/book-api
  serviceConfig:
    name:
    type: NodePort
    port: 3000
  deletionPolicy: Delete