apiVersion: samplecontroller.evan.com/v1alpha1
kind: Evan
metadata:
  name: example
  namespace: default
spec:
  deploymentConfig:
    name: ovi
    replicas: 3
    image: evanraisul/book-api
  serviceConfig:
    type: NodePort
    port: 4444
  deletionPolicy: WipeOut
